openapi: '3.0.2'
info:
  title: PRAETOR API
  version: '1.0'
  description: "APIs for PRAETOR project."
servers:
  - url: 'http://localhost:3000/'
    description: PRAETOR server.


components:
  schemas:
  
    Endpoint:
      description: Model containing endpoint info.
      type: object
      properties:
        coutry:
          type: string
          example: Luxembourg
        status:
          type: boolean
          example: true
          
    Endpoints:
      description: Array of endpoints.
      type: array
      items:
        $ref: '#/components/schemas/Endpoint'
        
    Crime:
      description: Model containing a specific crime's info.
      type: object
      properties:
        name:
          type: string
          description: Name of the crime.
          example: Robbery
        n_crimes:
          type: integer
          description: Number of crime's occurrencies in the specified year.
          example: 54
          
    YearData:
      description: Model containing crime data for a specific year.
      type: object
      properties:
        year:
          type: integer
          description: Year of data.
          example: 2019
        crimes:
          type: array
          description: Array of crimes occurred in that year.
          items:
            $ref: '#/components/schemas/Crime'
        
    CountryData:
      description: Crime data of a country.
      type: object
      properties:
        country:
          type: string
          description: Name of the country.
          example: Luxembourg
        year_data:
          type: array
          description: Array of data divided by year.
          items:
            $ref: '#/components/schemas/YearData'

    
paths:
  /api/endpoints:
    get:
      description: Gets the status of all countries' endpoints.
      
      responses:
        200:
          description: Endpoints successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Endpoints'

  /api/endpoints/{country}:
    get:
      description: Gets the status of a specific country's data endpoints.
      parameters:
        - in: path
          name: country
          description: The name of the country.
          required: true
          schema:
            type: string
            example: Luxembourg
      responses:
        200:
          description: Endpoint successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Endpoint'
                
  /api/data/{country}/{year}:
    get:
      description: Gets data for the specified country.
      parameters: 
        - in: path
          name: year
          required: true
          schema:
            type: integer
            description: Year.
            example: 2019
        - in: path
          name: country
          required: true
          schema:
            type: string
            description: The name of the country.
            example: Luxembourg
            
      responses:
        200:
          description: Data succesfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryData'
                
  /api/years/{country}:
    get:
      description: Gets available years for a selected country.
      parameters:
        - in: path
          name: country
          required: true
          schema:
            type: string
            description: Country.
            example: Luxembourg.
      
      responses:
        200:
          description: Years succesfully returned.
          content:
            application/json:
              schema:
                type: array
                example: [2017, 2018, 2019]
                items:
                  type: integer
                  
  /api/countries:
    get:
      description: Gets a list of all available countries.
      
      responses:
        200:
          description: Countries succesfully returned.
          content:
            application/json:
              schema:
                type: array
                example: ['Luxembourg', 'Italy', 'France']
                items:
                  type: string
                  
  /api/countries/{country}:
    get:
      description: Gets a list of all available regions of a given country.
      parameters: 
        - in: path
          name: country
          required: true
          schema:
            type: string
            description: Country.
            example: Luxembourg.
            
      responses:
        200:
          description: Regions succesfully returned.
          content:
            application/json:
              schema:
                type: array
                example: [Redange, Wiltz, Remich]
                items:
                  type: string
