openapi: '3.0.2'
info:
  title: PRAETOR API
  version: '1.0'
  description: "APIs for PRAETOR project."
servers:
  - url: 'http://localhost:3000/'
    description: PRAETOR server.


components:
  schemas:
  
    Endpoint:
      description: Model containing endpoint info.
      type: object
      properties:
        coutry:
          type: string
          example: Luxembourg
        status:
          type: boolean
          example: true
          
    Endpoints:
      description: Array of endpoints.
      type: array
      items:
        $ref: '#/components/schemas/Endpoint'
        
    Data:
      description: Crime data of a country.
      type: object
      properties:
        country:
          type: string
          example: Luxembourg
        crime_type:
          type: string
          example: Robbery
        stats:
          type: integer
          example: 54

    
paths:
  /endpoints:
    get:
      description: Gets the status of all countries' endpoints.
      
      responses:
        200:
          description: Endpoints successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Endpoints'

  /endpoints/{country}:
    get:
      description: Gets the status of a specific country's data endpoints.
      parameters:
        - in: path
          name: country
          required: true
          schema:
            type: string
            description: The name of the country.
            example: Luxembourg
      responses:
        200:
          description: Endpoint successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Endpoint'
                
  /data/{country}:
    get:
      description: Gets data for the specified country.
      parameters: 
        - in: path
          name: country
          required: true
          schema:
            type: string
            description: The name of the country.
            example: Luxembourg
            
      responses:
        200:
          description: Data succesfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
                

